### ISSUE TITLE
Milestone 1 - Deadline 28 Oct

### ISSUE THREAD

**Issue by veronwklai** [veronwklai/Design-Responsibly---create-a-healthy-internet-for-our-children-and-young-people#4]
Getting 3 people to involve

**Comment by veronwklai** [comment]
- [ ] Getting a delivery manager onboard 
- [ ] Getting students to support MozFest (and continue the project at UAL)
- [ ] Getting a social worker to help in MozFest

**Comment by veronwklai** [comment]
we have 5 people! More than what we set in the target :)
